<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR7f3c8b\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR7f3c8b/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR7f3c8b.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR7f3c8b\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR7f3c8b\App_KernelDevDebugContainer([
    'container.build_hash' => 'R7f3c8b',
    'container.build_id' => '2649f114',
    'container.build_time' => 1744714295,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR7f3c8b');
