<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJkgY6oj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJkgY6oj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJkgY6oj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJkgY6oj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJkgY6oj\App_KernelDevDebugContainer([
    'container.build_hash' => 'JkgY6oj',
    'container.build_id' => '485ef45c',
    'container.build_time' => 1744724255,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJkgY6oj');
